spring.application.name=inventario

# CONEXIÓN A AZURE SQL DATABASE
spring.datasource.url=jdbc:sqlserver://inventariodb-yamisa.database.windows.net:1433;database=inventario_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminyamisa@inventariodb-yamisa
spring.datasource.password=tiendaYamisa123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Tamaño de archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Seguridad JWT
security.jwt.secret=change_this_secret_in_production_please
security.jwt.expiration=86400000

# API PERU
api.peru.token=25c22d748dc267036061f6dcc1a71865e0bf44f999f75a9e4b828829026794f7
